export const content = {
  brand: {
    name: 'YOG SANYOG',
    tagline: 'Authentic Yoga, Mindful Living & Holistic Wellness',
    location: 'Kolkata, West Bengal',
    copyright: '© 2026 YOG SANYOG Studio & Academy. All rights reserved.',
  },
  nav: {
    home: 'Home',
    about: 'About Us',
    centre: 'Offline Centre',
    courses: 'Online Courses',
    contact: 'Contact',
    login: 'Log In',
    signup: 'Join Academy',
    dashboard: 'Dashboard',
    learn: 'My Courses',
    admin: 'Admin Panel',
    logout: 'Log Out',
  },
  home: {
    heroTitle: 'Harmonize Mind, Body & Soul with Traditional Wisdom',
    heroSubtitle: 'Personalized offline batches in West Bengal & self-paced online courses worldwide. Guided by certified traditional yoga masters.',
    ctaPrimary: 'Explore Online Courses',
    ctaSecondary: 'Visit Offline Studio',
    stats: [
      { label: 'Active Practitioners', value: '1,200+' },
      { label: 'Certified Instructors', value: '12+' },
      { label: 'Online Modules', value: '25+' },
      { label: 'Years of Tradition', value: '15+' },
    ],
    aboutStripTitle: 'Where Ancient Science Meets Modern Practice',
    aboutStripText: 'At YOG SANYOG, we blend classical Ashtanga, Hatha, and Pranayama practices with individual wellness goals. Whether you join our peaceful studio in West Bengal or learn online, we nurture your personal journey.',
    featuredCoursesTitle: 'Featured Online Courses',
    featuredCoursesSubtitle: 'Master traditional techniques at your own pace with video lessons & comprehensive PDF guides.',
    centreHighlightTitle: 'Join Our Offline Studio Centre',
    centreHighlightSubtitle: 'Experience small, focused batch sizes with real-time feedback and personal posture correction.',
    testimonialsTitle: 'Practitioner Stories',
    faqTitle: 'Frequently Asked Questions',
    finalCtaTitle: 'Begin Your Mindful Journey Today',
    finalCtaSubtitle: 'Join our welcoming community in person or start your digital course today.',
  },
  centre: {
    title: 'YOG SANYOG Offline Centre',
    addressLabel: 'Studio Location',
    address: '42 Lotus Heights, Sector III, Salt Lake, Kolkata, West Bengal 700106',
    timingsLabel: 'Centre Timings',
    timings: 'Monday – Saturday: 06:00 AM – 08:30 PM (Sunday Closed)',
    phoneLabel: 'Phone & Queries',
    phone: '+91 98300 12345',
    whatsappLabel: 'WhatsApp Chat',
    whatsappText: 'Chat on WhatsApp',
    mapPlaceholder: 'Interactive Map View (Salt Lake Centre)',
  },
  courses: {
    title: 'Explore Our Courses',
    subtitle: 'From foundational Pranayama to advanced Vinyasa flow.',
    filterCategory: 'Category',
    filterLevel: 'Level',
    searchPlaceholder: 'Search courses by title or keyword...',
    empty: 'No courses matched your search criteria.',
    buyNow: 'Enroll Now',
    previewLesson: 'Preview Syllabus',
  },
  checkout: {
    title: 'Complete Your Order',
    summaryTitle: 'Order Summary',
    payButton: 'Pay with Razorpay (Stub)',
    successTitle: 'Payment Successful!',
    successSubtitle: 'Your course access has been granted. Get ready to begin your practice.',
    failedTitle: 'Payment Failed',
    failedSubtitle: 'Something went wrong during transaction processing. Please try again.',
  },
  student: {
    welcome: 'Welcome back,',
    batchCardTitle: 'My Batch Details',
    feeSummaryTitle: 'Fee Dues & Status',
    latestAnnouncement: 'Recent Announcement',
    payDues: 'Pay Outstanding Fees',
  },
  admin: {
    dashboardTitle: 'Admin Overview',
    studentsTitle: 'Student Roster',
    batchesTitle: 'Batch Management',
    feesTitle: 'Fee Tracking & Receipts',
    coursesTitle: 'Course Management',
    leadsTitle: 'Incoming Enquiries',
  },
  common: {
    loading: 'Loading content...',
    error: 'An unexpected error occurred. Please try again.',
    retry: 'Retry',
    save: 'Save Changes',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    submit: 'Submit',
    success: 'Success',
    close: 'Close',
  },
} as const;

export type ContentDictionary = typeof content;
